name: Mario Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Mario Graph
        run: |
          mkdir -p dist
          python3 .github/workflows/generate_mario_graph.py

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Mario Contribution Graph"
          branch: output
          file_pattern: "dist/mario-graph.svg"
